### ISSUE TITLE
Next Release

### ISSUE THREAD

**Issue by thomasklemm** [jnicklas/memoit#7]
Hi Jonas, https://github.com/jnicklas/memoit/commit/cd6abf702673492fe6822cc4431fbe90119856a2 for handing `query?` and `bang!` methods is still unreleased. It would be great if you could push a new release to Rubygems on occasion. Thanks :)

**Comment by jnicklas** [comment]
Done!

**Comment by thomasklemm** [comment]
Cool, thanks!
