### ISSUE TITLE
RSpec allow_any_instance_of and memoit don't get along

### ISSUE THREAD

**Issue by henrik** [jnicklas/memoit#9]
Afraid I don't want to dig into this now, but I'll write it up at least:

If you use these two on the same method, you can get errors like

    super: no superclass method `my_method' for `<MyClass:0xf00>`

It's very rare that I use `allow_any_instance_of` but in this case I "had" to, to make some old code work for another week until I can remove it.

This was with RSpec 2.14.1.

Might not be worthwhile to try to fix this, but I thought I'd mention it so it's googleable if nothing else.

**Comment by jnicklas** [comment]
Huh. I don't really think there's anything we can do about this.

**Comment by henrik** [comment]
Yeah, I would guess RSpec undefines the method and does some black magic. I'll close the ticket.
